Patrimonio/grails-app/domain/patrimonio/BensdeConsumo.groovy
package patrimonio

class BensdeConsumo {
   
    static constraints = {
    }
}

Patrimonio/grails-app/controllers/patrimonio/BensdeConsumoController.groovy
package patrimonio



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class BensdeConsumoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond BensdeConsumo.list(params), model:[bensdeConsumoInstanceCount: BensdeConsumo.count()]
    }

    def show(BensdeConsumo bensdeConsumoInstance) {
        respond bensdeConsumoInstance
    }

    def create() {
        respond new BensdeConsumo(params)
    }

    @Transactional
    def save(BensdeConsumo bensdeConsumoInstance) {
        if (bensdeConsumoInstance == null) {
            notFound()
            return
        }

        if (bensdeConsumoInstance.hasErrors()) {
            respond bensdeConsumoInstance.errors, view:'create'
            return
        }

        bensdeConsumoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'bensdeConsumo.label', default: 'BensdeConsumo'), bensdeConsumoInstance.id])
                redirect bensdeConsumoInstance
            }
            '*' { respond bensdeConsumoInstance, [status: CREATED] }
        }
    }

    def edit(BensdeConsumo bensdeConsumoInstance) {
        respond bensdeConsumoInstance
    }

    @Transactional
    def update(BensdeConsumo bensdeConsumoInstance) {
        if (bensdeConsumoInstance == null) {
            notFound()
            return
        }

        if (bensdeConsumoInstance.hasErrors()) {
            respond bensdeConsumoInstance.errors, view:'edit'
            return
        }

        bensdeConsumoInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'BensdeConsumo.label', default: 'BensdeConsumo'), bensdeConsumoInstance.id])
                redirect bensdeConsumoInstance
            }
            '*'{ respond bensdeConsumoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(BensdeConsumo bensdeConsumoInstance) {

        if (bensdeConsumoInstance == null) {
            notFound()
            return
        }

        bensdeConsumoInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'BensdeConsumo.label', default: 'BensdeConsumo'), bensdeConsumoInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'bensdeConsumo.label', default: 'BensdeConsumo'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

Patrimonio/grails-app/views/bensdeConsumo/_form.gsp
<%@ page import="patrimonio.BensdeConsumo" %>



<div class="fieldcontain ${hasErrors(bean: bensdeConsumoInstance, field: 'descricao', 'error')} required">
	<label for="descricao">
		<g:message code="bensdeConsumo.descricao.label" default="Descricao" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="descricao" required="" value="${bensdeConsumoInstance?.descricao}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: bensdeConsumoInstance, field: 'foto', 'error')} required">
	<label for="foto">
		<g:message code="bensdeConsumo.foto.label" default="Foto" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="foto" required="" value="${bensdeConsumoInstance?.foto}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: bensdeConsumoInstance, field: 'quantidade', 'error')} required">
	<label for="quantidade">
		<g:message code="bensdeConsumo.quantidade.label" default="Quantidade" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="quantidade" required="" value="${bensdeConsumoInstance?.quantidade}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: bensdeConsumoInstance, field: 'tombamento_bc', 'error')} required">
	<label for="tombamento_bc">
		<g:message code="bensdeConsumo.tombamento_bc.label" default="Tombamentobc" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="tombamento_bc" type="number" value="${bensdeConsumoInstance.tombamento_bc}" required=""/>

</div>

Patrimonio/grails-app/views/bensdeConsumo/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'bensdeConsumo.label', default: 'BensdeConsumo')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-bensdeConsumo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-bensdeConsumo" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${bensdeConsumoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${bensdeConsumoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:bensdeConsumoInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Patrimonio/grails-app/views/bensdeConsumo/edit.gsp
<%@ page import="patrimonio.BensdeConsumo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'bensdeConsumo.label', default: 'BensdeConsumo')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-bensdeConsumo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-bensdeConsumo" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${bensdeConsumoInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${bensdeConsumoInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:bensdeConsumoInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${bensdeConsumoInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

Patrimonio/grails-app/views/bensdeConsumo/index.gsp
<%@ page import="patrimonio.BensdeConsumo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'bensdeConsumo.label', default: 'BensdeConsumo')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-bensdeConsumo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-bensdeConsumo" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="descricao" title="${message(code: 'bensdeConsumo.descricao.label', default: 'Descricao')}" />
					
						<g:sortableColumn property="foto" title="${message(code: 'bensdeConsumo.foto.label', default: 'Foto')}" />
					
						<g:sortableColumn property="quantidade" title="${message(code: 'bensdeConsumo.quantidade.label', default: 'Quantidade')}" />
					
						<g:sortableColumn property="tombamento_bc" title="${message(code: 'bensdeConsumo.tombamento_bc.label', default: 'Tombamentobc')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${bensdeConsumoInstanceList}" status="i" var="bensdeConsumoInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${bensdeConsumoInstance.id}">${fieldValue(bean: bensdeConsumoInstance, field: "descricao")}</g:link></td>
					
						<td>${fieldValue(bean: bensdeConsumoInstance, field: "foto")}</td>
					
						<td>${fieldValue(bean: bensdeConsumoInstance, field: "quantidade")}</td>
					
						<td>${fieldValue(bean: bensdeConsumoInstance, field: "tombamento_bc")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${bensdeConsumoInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

Patrimonio/grails-app/views/bensdeConsumo/show.gsp
<%@ page import="patrimonio.BensdeConsumo" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'bensdeConsumo.label', default: 'BensdeConsumo')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-bensdeConsumo" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-bensdeConsumo" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list bensdeConsumo">
			
				<g:if test="${bensdeConsumoInstance?.descricao}">
				<li class="fieldcontain">
					<span id="descricao-label" class="property-label"><g:message code="bensdeConsumo.descricao.label" default="Descricao" /></span>
					
						<span class="property-value" aria-labelledby="descricao-label"><g:fieldValue bean="${bensdeConsumoInstance}" field="descricao"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${bensdeConsumoInstance?.foto}">
				<li class="fieldcontain">
					<span id="foto-label" class="property-label"><g:message code="bensdeConsumo.foto.label" default="Foto" /></span>
					
						<span class="property-value" aria-labelledby="foto-label"><g:fieldValue bean="${bensdeConsumoInstance}" field="foto"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${bensdeConsumoInstance?.quantidade}">
				<li class="fieldcontain">
					<span id="quantidade-label" class="property-label"><g:message code="bensdeConsumo.quantidade.label" default="Quantidade" /></span>
					
						<span class="property-value" aria-labelledby="quantidade-label"><g:fieldValue bean="${bensdeConsumoInstance}" field="quantidade"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${bensdeConsumoInstance?.tombamento_bc}">
				<li class="fieldcontain">
					<span id="tombamento_bc-label" class="property-label"><g:message code="bensdeConsumo.tombamento_bc.label" default="Tombamentobc" /></span>
					
						<span class="property-value" aria-labelledby="tombamento_bc-label"><g:fieldValue bean="${bensdeConsumoInstance}" field="tombamento_bc"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:bensdeConsumoInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${bensdeConsumoInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>